src/credits.c

error correction and Pikalax's solution for `switch (sCreditsMgr->whichMon)`

closer RollCredits

---

asm/macros/event.inc
data/event_scripts.s
data/maps/CeladonCity_DepartmentStore_Roof/scripts.inc
data/maps/CeladonCity_GameCorner/scripts.inc
data/maps/CeruleanCity_BikeShop/scripts.inc
data/maps/FuchsiaCity_SafariZone_Entrance/scripts.inc
data/maps/PewterCity_Museum_1F/scripts.inc
data/maps/Route4_PokemonCenter_1F/scripts.inc

Pursuant to a recent discussion in the Emerald discord, it was agreed that the two nops (.byte 0, 0) following every instance of `hidemoneybox` should be hardcoded into the command macro definition.  The command took two one-byte arguments in Ruby and Sapphire but not any of the later titles.  However, these arguments were not properly dummied.

hidemoneybox buries dummy args now

---

.gitignore

Same reasoning I had when I proposed this change to Pokeruby's gitignore.
This format represents VisualBoyAdvance's save files. Since they're currently not being filtered out by .gitignore, these kind of files could be sent to a GitHub Repository via git push accidentally.

 Add VBA's save files to gitignore

---

sound/direct_sound_data.inc

The vanilla samples seem to be aligned naturally, but using any other samples causes them to break alignment, making the audio completely garbled.

align directsound samples

---

asm/field_screen_effect.s
asm/overworld.s
data/field_weather.s
ld_script.txt
src/field_screen_effect.c

Based on pokeemerald's [functions of the same name](https://github.com/pret/pokeemerald/blob/75b0c9d7a9edabc742bc42f19d078fa2ae64870c/src/field_screen_effect.c#L766,L801).
I'm not in love with `xy` and `yx` as variable names (although it's definitely more indicative of their use than pokeemerald's `r` and `v3`). The fact that they get used in both orders for x and y makes it tricky to name them.
It was also surprisingly difficult for me to put what's going on into words, particularly because the code is implemented _slightly_ differently to how I would do it. If anything is unclear please ask, and I'll try to explain and reflect that explanation in the comment.

Describe flash scanline effect

---

asm/macros/map.inc
data/maps/CeladonCity/map.json
data/maps/CeruleanCity/map.json
data/maps/FiveIsland/map.json
data/maps/Route15/map.json
data/maps/Route2/map.json
data/maps/Route21_North/map.json
data/maps/Route4/map.json
data/maps/Route7/map.json
data/maps/SevenIsland_SevaultCanyon_Entrance/map.json
tools/mapjson/mapjson.cpp

These are the objects which are positioned in the connection to a different map, indicated by having the field after graphics id set to 0xFF rather than 0. With a few exceptions (the Fat Man in Pallet Town coming from 21, the NPC guarding Cerulean Cave coming from Route 4, and a trainer on the bridge in Sevault Canyon Entrance) all of them are Cut Trees. By definition their coordinates are outside the bounds of the map, and can be negative.
~~This is sort of an interim solution, it might be preferable if the field was a bool. Alternatively the field could be renamed, listed for all object events, and have two constants like `OBJ_IN_CONNECTION` for 255 and `OBJ_IN_MAP` for 0~~
updated to bool

Split connection field from graphics id in object events

---

include/battle_script_commands.h

These are already present in include/constants/battle_script_commands.h
I tend to screw things up a lot, so if anyone sees anything wrong here please let me know.

Removed unused defines in include/battle_script_commands.h

---

.travis.yml

Required since devkitPro decided to delete the version we were using.

Bump devkitARM to r52

---

tools/gbagfx/main.c
tools/gbagfx/util.c
tools/gbagfx/util.h

- Fix num_colors exceeding amount of colors in palette leading to use of uninitialized colors
- Handle png -> pal conversion (aka extracting JASC palettes from png)
- Allow JASC pal files to be used as -palette argument when converting from GBA to PNG
- Allow using only file extension as output to reuse entire path from input before extension

gbagfx: Various fixes and improvements

---

.gitignore
include/librfu.h
src/librfu_rfu.c

After decompiling librfu v1.0.21, I confirmed the difference of API buffer size between SDK manual and header is very likely caused by carelessness. In v1.0.21, it's really using the constants in header which is 0x28 bytes larger than that in the manual. 
This is because, in v1.0.21, some fields in latest `struct RfuStatic` were placed in `.bss` as separate variables, so `struct RfuStatic` is 0x10 bytes smaller there. and for some unknown reason, the API buffer was designed to hold 2 more `struct RfuSlotStatusUNI` (both unused I believe, maybe this is the change indicated by `* Removed all of the RFU library variables related to key sharing.`)
so the difference can be computed as: -2 * (sizeof(struct RfuSlotStatusUNI)) + 0x10 = -0x28.

fix librfu issues

---

include/fieldmap.h

`VIRTUAL_MAP_SIZE` is an assert name, `MAX_MAP_DATA_SIZE` is clearer and used by pokeemerald/porymap

Add MAX_MAP_DATA_SIZE alias

---

src/data/wild_encounters.json

Adds the missing `MAP_` prefix to the map names in LeafGreen's `"map"` fields in `src/data/wild_encounters.json`. This allows LeafGreen's encounters to be edited in porymap.

wild_encounters.json: Add "MAP_" prefix to LeafGreen's "map" fields

---

asm/macros/music_voice.inc
sound/voice_groups.inc

Also explicitly align voicegroups since they weren't for some reason.
Besides that, same changes as [#1195](https://github.com/pret/pokeemerald/pull/1195) from pokeemerald.

Update Audio Macros

---

src/pokemon.c

This not using a constant causes a long freeze when releasing pokemon if a new move is added

Fix hang when releasing after adding new moves

---

src/main_menu.c

There were two lines where magic numbers were used instead of the constant for MAIN_MENU_WINDOW_ERROR, so I filled them in.

Fix Missed Magic Numbers in main_menu.c

---

src/pokemon.c

Whoever originally decomped this function must've been really fed up with this file.
Renamed GetMUS_ForBattle to GetBattleBGM to be consistent with pokeemerald.
This entire function was magic numbers, so I replaced them with the appropriate constants.

Fix Egregious Magic Numbers in GetBattleBGM

---

data/maps/VermilionCity_Gym/scripts.inc
data/maps/VermilionCity_Gym/text.inc

The script labels for being given TM34 from Lt. Surge are mistakenly typoed as TM43. This commit fixes this error.

Fix Vermilion Gym Script Label Transposition Typos

---

include/constants/daycare.h
src/daycare.c

Someone misspelled "compatibility" as "compatability" in pokeemerald and the error was brought over to pokefirered.

Fix "Compatibility" Misspelling

---

data/maps/CeladonCity_Condominiums_RoofRoom/scripts.inc
include/global.h
src/field_player_avatar.c
src/pokemon.c

The Celadon City scripts that give Eevee misspelled it as Eeevee. Fixed.
The comment explaining `boxRSEggsUnlocked` in the `ExternalEventFlags` struct had an incorrect deposit requirement listed and was fixed.
Also, replaced the literals with the `TOTAL_BOXES_COUNT` and `IN_BOX_COUNT` constants in `pokemon.c`'s `IsPokemonStorageFull` function. Thanks hjk321 for pointing that out.
`gUnknown_835B882` has been cleaned up and renamed to `sPlayerAvatarGfxToStateFlag` to match pokeemerald. Thanks Spherical Ice for pointing it out.

Fix Typos / Use Box Constants / Name an Unknown

---

src/trade.c

Taken from [this](https://gitlab.com/RadicalDweamer/pokefirered/-/commit/c1293f2245e049bd2c8c69dead4031fed89f4c77) commit by shoomer/RadicalDweamer and edited to have only necessary changes.
Change to the dummy variable is not required for matching, but it doesn't need to be volatile to match, so it seems like a good idea to let the (modern) compiler optimize it out.

Fix Trade Nonmatchings (Thanks to Shoomer/RadicalDweamer)

---

src/battle_bg.c

Replacing several instances of a hardcoded 9 in reference to terrain with the macro BATTLE_TERRAIN_PLAIN

Using macro for plain terrain instead of hardcoded numbers

---

src/battle_anim_effects_1.c

Fixes UB on modern compilers--literally copypasted the func from emerald.

Port Protect Animation Fix from Emerald

---

src/new_game.c

`sub_80549D4` -> `ClearBattleTower`
As discussed in Discord
Discord: sesese9#1678

[New Game] Name single func

---

src/oak_speech.c

`unk_0010` is only ever used as a boolean check for whether the player has been named or not, to differentiate the state of the intro naming tasks (whether you're naming the player or the rival), so suggest renaming to `hasPlayerBeenNamed`.
`data[1]` stores the horizontal offset of BG2 (where the trainer pics are rendered), so suggest #defining it as `tTrainerPicPosX`.
`data[2]` stores the state of the fade in/out (blending) of BG2 (value 0 when no fading is active), so suggest #defining it as `tTrainerPicFadeState`.
Since the trainer pics (Male/female player, Rival and Oak) in BG2 are always loaded with the same IDs, also thinks this reads cleaner as an enum.

Document fields in oak_speech

---

include/battle_gfx_sfx_util.h
src/battle_gfx_sfx_util.c

Addressing a trivial TODO by giving the `notTransform` argument to `handleSpeciesGfxDataChange` a more appropriate name for FireRed, and adding comments explaining what it represents.

Some documentation of transform types

---

src/pokemon.c

Someone added a bugfix preproc directive without ever defining it anywhere, leaving that up to the user, instead of using the already defined and already used `BUGFIX` constant.
This PR "solves" that.
**EDIT**: Lmao, it was Revo, 4 years ago, well before `BUGFIX` was established. Still, I guess this PR still holds some value in keeping the `BUGFIX`es consistent in how they're handled in this project.
Lunos#4026

Replaced undefined BUGFIX_SETMONIVS with good ol' BUGFIX

---

include/config.h
include/gba/isagbprint.h
include/mini_printf.h
src/isagbprn.c
src/main.c
src/mini_printf.c

Syncing changes from https://github.com/pret/pokeemerald/pull/1768, https://github.com/pret/pokeemerald/pull/1827, and https://github.com/pret/pokeemerald/commit/603d870ea0f4fb510a894bde4a1f999a021c9ac9
Point of difference: because FR/LG don't have `NDEBUG` defined by default, for matching purposes `LOG_HANDLER` has been set to `LOG_HANDLER_AGB_PRINT` instead of `LOG_HANDLER_MGBA_PRINT` and `PRETTY_PRINT_HANDLER` has been set to a new `PRETTY_PRINT_OFF` instead of `PRETTY_PRINT_MINI_PRINTF`.
Additionally, the repo wouldn't compile with `NDEBUG` defined because the linker expected the symbols defined in `common_syms/main.txt` to exist, so the conditional there was removed.

Sync debug print functions

---

INSTALL.md

Apple Silicon Macs new default bash installs Homebrew in a different directory than Intel macs, and thus breaks compatibility of some of the build commands as libpng would be installed in the wrong location. New notes are added specifically for Apple Silicon Mac users to ensure brew and libpng are installed in the proper location.
Example Error:
**convert_png.c:5:10: fatal error: 'png.h' file not found**
There was previous discussion in the pokeemerald discord that helped verify these additional requirements for Apple Silicon Macs, and thus should also be changed in that repo's INSTALL.md

Updates to INSTALL.md for Apple Silicon Macs

---

src/data/graphics/trainers.h

Not sure if maybe this is an idiosyncrasy of pkmn fire red, but it looks like it's probably just a typo; Red and Leaf each use the other's back pic palette

Red and Leaf back palettes swapped

---

tools/gbagfx/Makefile
tools/rsfont/Makefile

This PR comes originally from @GriffinRichards found here: https://github.com/pret/pokeemerald/pull/1645/files
All I've done is add it to Fire Red to fix building on macOS.

Fix macOS building

---

src/party_menu.c

While both compile to the same output when doing test functions in https://cexplore.karathan.at/, shinny pointed in the discord that, if you expand TMs, using ITEM_TM50 would break things.
Using ITEM_HM01 was the previous behaviour, it was changed by cbt when documented the party menu.
This was pointed out but HunarPG in the pokefirered Discord channel.

Compare to ITEM_HM01 and not ITEM_TM50

---

src/data/trainer_parties.h
src/data/trainers.h

Missed these when implementing commit 93d4e3ff66b4b96dd8f69761edf99fdfa3873bad

Fix misspelling: RivalPokenonTower -> RivalPokemonTower

---

data/map_events.s
tools/mapjson/mapjson.cpp

As we discovered, map event scripts must be aligned to 4 bytes; this happens naturally in vanilla, so there were never any explicit alignment directives added, but when using the modern linkerscript, there is no such guarantee. The alignment is now guaranteed in two places: both at the start of the overall map event data blob and at the start of each map `events.inc` file. Theoretically, just aligning the data blob should be enough to ensure alignment for every map script, so this may be excessive, but it could be helpful if someone does some weird unlikely change down the line (though I fail to think of a use case that would necessitate such a change).

Ensure Alignment for Map Events

---

include/util.h
src/field_effect.c
src/trainer_see.c
src/util.c

GCC 14 treats implicit pointer conversions as errors, so edits are needed to compile in modern. However, this is already how we're doing it in pokeemerald anyway, so this is more of a sync than anything.

Fix Compilation on GCC 14

---

Makefile
include/gba/defines.h
ld_script.ld
ld_script_modern.ld

Ported this from pokeemerald: https://github.com/pret/pokeemerald/pull/1952
No dependencies on other PRs
- The linkerscript should warn if memory bounds are exceeded.
- Running `make` now prints memory usages
Example output:
```bash
Memory region         Used Size  Region Size  %age Used
EWRAM:      261040 B       256 KB     99.58%
IWRAM:         32 KB        32 KB    100.00%
ROM:    15403808 B        32 MB     45.91%
```
**Discord contact info**
merrp

Linkerscript now tracks RAM/ROM usage

---

src/battle_script_commands.c
src/mon_markings.c

Decodes the following values as Japanese text:
- `sUnused` in `battle_script_commands.c` is unused Japanese text for "Turn". It's also [present in Ruby/Sapphire](https://github.com/pret/pokeruby/blob/714bd0ac0e38fa4ee51a11f7679ea91f6ce6762b/src/battle_controller_player.c#L229), where it's used in [debug code](https://github.com/pret/pokeruby/blob/714bd0ac0e38fa4ee51a11f7679ea91f6ce6762b/src/battle_controller_player.c#L756).
- `sUnused` in `mon_markings.c` is unused Japanese text for "Confirm".

Decode unused JP text

---

src/event_object_movement.c

`FindCameraObject` can return `NULL`. Other functions handle this. Not sure if this can ever occur in vanilla.

Fix for potential UB in CameraObjectReset2

---

src/battle_transition.c

When starting a wild cave encounter `InitBlackWipe` is called in `ClockwiseWipe_TopRight` with -1 for `endY`. This results in `sTransitionData->tWipeCurrY` ending up being -1 aswell, which is then used to access `gScanlineEffectRegBuffers[0][sTransitionData->tWipeCurrY]` leading to UB.
.cawt

UB fix in battle_transition.c

---

data/maps/TwoIsland_House/scripts.inc
data/specials.inc
src/learn_move.c
src/party_menu_specials.c

This renames `SelectMoveTutorMon` and `DisplayMoveTutorMenu` to `ChooseMonForMoveRelearner` and `TeachMoveRelearnerMove`, respectively.
This is how they're named in pokeemerald, and it avoids `SelectMoveTutorMon` from being confused with the similar  `ChooseMonForMoveTutor`.

Rename the Move Relearner specials

---

include/constants/global.h
include/item_menu.h
src/item.c
src/item_menu.c

There is already a define for the total number of pockets (`NUM_BAG_POCKETS`), but there is not one for the number of pockets not including the TM case and berry pouch, which are separate menus from the 3 main pockets. I have created the constant `NUM_BAG_POCKETS_NO_CASES` to deal with this as there are various loops and structs that refer to this quantity. Feedback is welcome on the name, I'm not totally happy with it but couldn't think of anything better.

Add Constant for 3 Main Bag Pockets

---

Makefile

Current makefile puts compiler temps in the top-level directory where they are not gitignored and where they potentially clutter the source tree. This restores a previous behavior where these files are instead placed inside build/ as they should be.

.i and .s files should be under build/ when KEEP_TEMPS=1

---

src/start_menu.c

While I was trying to help someone over at PokeCommunity I noticed that in order to quickly remove access to one of the game's start menu options, one had to update not only the places where said start menu option's `STARTMENU` label is used, but also `sStartMenuActionTable`, the table that links each start menu option's text string and main callback function together.
Since this connection might not be obvious to potential users, I decided to quickly link the `STARTMENU` labels with the entries on that table to make it easier to understand.
Aligning the table's labels was an extra, something I just did it on a whim :P ... let me know if it was uncalled for.
lunos4026

Linked STARTMENU labels to the entries of sStartMenuActionTable

---

Makefile
include/gba/m4a_internal.h
include/global.h
include/librfu.h
include/pokemon.h
src/daycare.c
src/field_player_avatar.c
src/librfu_intr.c
src/m4a.c
src/pokemon.c
src/vs_seeker.c
tools/mapjson/json11.cpp

This mostly syncs all the needed checks to able to compile with different gcc versions, this affects distros like arch when trying to build with MODERN compiler.
Credits to:
- Kurausukun: https://github.com/pret/pokeemerald/pull/2138 and https://github.com/pret/pokeemerald/pull/2144/
- Hedara: https://github.com/pret/pokeemerald/commit/c8d3a6b4dfa7f10a8c7bce619e7ed5961d4f356e
- mrgriffin: https://github.com/pret/pokeemerald/pull/1756
Feel free to squash and merge since I missed some checks in m4a.c and had to make another commit.

Modern fixes
