pret/pokefirered

INSTALL.md

Adjusted to match the recent changes.

Refresh INSTALL.md

---

include/bg.h
src/bg.c

At least better than inline ASM I guess

'real' match CopyTileMapEntry

---

src/util.c

Variable `tile` should be `u16`. The other problems are resolved in an ugly way.

'real' match CopySpriteTiles

---

src/battle_transition.c

'real' match BT_Phase2FullScreenWave_UpdateWave

---

src/menu2.c

Sadly the clobber has to be there (or at the end of each iteration, which doesn't matter) for me

attempt sub_812E768

---

include/text.h
src/braille_text.c
src/text.c
src/text_printer.c

with var renaming to sync with pokeemerald

real match RenderText

---

src/quest_log.c

... Extremely weird way of bitfield access

real match sub_8110BE8

---

src/trade.c

no inline asm but not that real :(

'real' match sub_804F284

---

asm/macros/event.inc
data/event_scripts.s
data/maps/CeladonCity_DepartmentStore_Roof/scripts.inc
data/maps/CeladonCity_GameCorner/scripts.inc
data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.inc
data/maps/CinnabarIsland_Gym/scripts.inc
data/maps/FuchsiaCity_SafariZone_Entrance/scripts.inc
data/maps/PewterCity_Museum_1F/scripts.inc
data/maps/RocketHideout_B1F/scripts.inc
data/maps/Route4_PokemonCenter_1F/scripts.inc
data/script_cmd_table.inc
data/scripts/obtain_item.inc
include/coins.h
src/coins.c
src/scrcmd.c
src/slot_machine.c

Based on review from pret/pokeemerald#953

Sync macros to have Give/Take Add/Remove unity

---

.gitignore
data/maps/PewterCity/map.json
data/maps/PewterCity/scripts.inc
data/maps/PewterCity/text.inc
data/maps/PewterCity_Gym/map.json
data/maps/PewterCity_Gym/scripts.inc
data/maps/PewterCity_Gym/text.inc
data/maps/PewterCity_House1/map.json
data/maps/PewterCity_House1/scripts.inc
data/maps/PewterCity_House1/text.inc
data/maps/PewterCity_House2/map.json
data/maps/PewterCity_House2/scripts.inc
data/maps/PewterCity_House2/text.inc
data/maps/PewterCity_Mart/map.json
data/maps/PewterCity_Mart/scripts.inc
data/maps/PewterCity_Mart/text.inc
data/maps/PewterCity_Museum_1F/map.json
data/maps/PewterCity_Museum_1F/scripts.inc
data/maps/PewterCity_Museum_1F/text.inc
data/maps/PewterCity_Museum_2F/map.json
data/maps/PewterCity_Museum_2F/scripts.inc
data/maps/PewterCity_Museum_2F/text.inc
data/maps/PewterCity_PokemonCenter_1F/map.json
data/maps/PewterCity_PokemonCenter_1F/scripts.inc
data/maps/PewterCity_PokemonCenter_1F/text.inc
data/scripts/fame_checker.inc
data/scripts/mystery_event_club.inc
data/text/fame_checker.inc

Diff struggled to resolve the `walk_to_dest` macros in the PewterCity script

Document Pewter City scripts

---

tools/gbafix/gbafix.c

Syncing with pret/pokeemerald#804

Remove extraneous parens in gbafix

---

.travis/calcrom/calcrom.pl

Syncing with pret/pokeemerald#955

Remove false positives from partial doc calcrom

---

src/pokemon.c

sCombinedMoves

---

data/maps/VermilionCity/scripts.inc
data/mystery_event_msg.s
include/constants/flags.h

Syncing with pret/pokeemerald#991

Sync event ticket flag names

---

src/learn_move.c

Describe and label the move relearner state machine cases.

move_relearner_state_machine_defines

---

data/battle_anim_scripts.s
include/battle_anim.h
src/battle_anim_effects_1.c
src/battle_anim_effects_2.c
src/battle_anim_effects_3.c
src/battle_anim_mon_movement.c
src/battle_anim_mons.c
src/battle_anim_sound_tasks.c
src/battle_anim_special.c
src/battle_anim_status_effects.c
src/battle_anim_utility_funcs.c
src/bug.c
src/dark.c
src/dragon.c
src/electric.c
src/fighting.c
src/fire.c
src/flying.c
src/ghost.c
src/ground.c
src/ice.c
src/normal.c
src/poison.c
src/psychic.c
src/rock.c

document data/battle_anim_scripts.s and corresponding src files similar to pokeemerald

battle anim documentation

---

include/librfu.h
src/librfu_rfu.c

fix remainSize field in librfu

---

src/decompress.c

Refer to https://github.com/pret/pokeruby/pull/783 for details

Decompile unused decompress function, as seen in ruby

---

src/battle_transition.c

side note: this one was one of the trickiest matchings, mostly because the chain assignments.

Match sub_80D1F64

---

asm/crt0.s
asm/libagbsyscall.s
berry_fix/asm/loader.s
berry_fix/payload/asm/libagbsyscall.s
include/list_menu.h
include/quest_log.h
src/battle_script_commands.c
src/help_message.c
src/link_rfu_3.c
src/list_menu.c
src/m4a.c
src/menu.c
src/pokedex_screen.c
src/water.c

So this is pretty much all of the functions I was able to match. I am currently stuck on the others, as in Emerald, but now we are down to under 10 naked functions now in FireRed!

Match (Most of) Firered

---

src/agb_flash.c

Fixes issue where the game would crash on boot when compiled with gcc-10.

Fix agb_flash in modern frlg

---

src/m4a.c

For details, see [the pokeemerald PR](https://github.com/pret/pokeemerald/pull/1232).

Match FadeOutBody (ported from pokeemerald)

---

data/pokedex_screen.s

Renames some of the "Unknown" variables to match their purpose

Give meaningful names to globals in pokedex_screen.s

---

src/data/trainer_parties.h
src/data/trainers.h

Rename unknown trainer party variables

---

include/pokemon.h
src/pokemon.c

I really don't know how this survived for so long.

Change embarassing magic numbers that should have been fixed a long time ago

---

Makefile

Popped up in the discord channel so PR'ing it. 
Discord: sesese9#1678

Add -DINFO Option to Makefile

---

src/berry_crush_2.c
src/mystery_gift_menu.c

Was just looking at the two following Kura mentioning we could backport some stuff. Found these two quick ones to backport

Backport 2 nonmatching fixes from emerald

---

src/librfu_rfu.c
src/trainer_tower.c

Trainer Tower fix is thanks to shoomer running the permuter. RFU fix is something I forgot to port from Emerald.

Fix Some Fakematchings

---

src/help_system_util.c
src/text.c

Credit for these goes to RadicalDweamer, whose [branch](https://gitlab.com/RadicalDweamer/pokefirered/-/tree/test) I took these from with minimal changes. Mostly found by using the permuter (apparently).

Fix 2 Fakematchings

---

src/m4a.c

ON THIS MOST HALLOWED OF NIGHTS, THE BEAST KNOWN ONLY AS CGBMODVOL HAS BEEN SLAIN BY THE VALIANT WARRIOR POKEREVOTPP. LET US REJOICE IN HIS CONQUEST!

FIX CGBMODVOL FAKEMATCHING (WE DID IT REDDIT)

---

src/librfu_intr.c
src/librfu_rfu.c
src/librfu_sio32id.c

Ports of PRs [#1411](https://github.com/pret/pokeemerald/pull/1411) and [#1412](https://github.com/pret/pokeemerald/pull/1412) from pokeemerald by Revo.
NONMATCHINGs was released outside. Bye-bye, NONMATCHINGs!

Fix Final 2 Nonmatchings (ported from emerald)

---

src/battle_interface.c

Taken from [#1426](https://github.com/pret/pokeemerald/pull/1426) from pokeemerald.

[LEAK-INFORMED] Fix battle_interface Fakematch

---

include/link.h
include/link_rfu.h
src/cable_club.c
src/link.c
src/link_rfu_2.c
src/link_rfu_3.c
src/mystery_gift_menu.c
src/pokemon_jump_2.c
src/union_room.c
src/union_room_chat.c

And then super-sync.
And then achieve a level _beyond_ super-sync!

Sync link rfu from Emerald

---

include/pokemon.h
src/daycare.c
src/evolution_scene.c

Ported from Emerald, see [the PR over there](https://github.com/pret/pokeemerald/pull/1455) for details.

[LEAK-INFORMED] Fix CreateShedinja Fakematch

---

.github/workflows/build.yml
Makefile

Ported action from [pokeruby](/pret/pokeruby)

Create symfiles on build

---

Makefile

Sync from pret/pokeemerald#1465

Symplifi symfiles

---

src/malloc.c

Fix Dumb Alloc/AllocZeroed Issue

---

include/config.h
include/global.h
src/agb_flash.c
src/battle_ai_script_commands.c
src/battle_anim_mons.c
src/battle_script_commands.c
src/easy_chat.c
src/event_object_movement.c
src/field_effect.c
src/fieldmap.c
src/pokemon_storage_system_7.c
src/sprite.c
src/union_room.c

Includes the save fix on modern -O3. These are just things I tried while fixing the other issue, but they should probably be ported either way.

Port UBFIX Macro and Some Usages from Emerald

---

.github/workflows/build.yml

Use merge commit message for symbols branch

---

include/player_pc.h
src/mailbox_pc.c
src/party_menu.c
src/player_pc.c

Fixes a discrepancy between these struct fields and the list menu API

Swap two fields in player PC struct

---

.github/workflows/build.yml

Syncing with https://github.com/pret/pokeemerald/pull/1495

Fix symbols branch commit messages

---

include/gba/m4a_internal.h
include/m4a.h
src/m4a.c

See [#1492](https://github.com/pret/pokeemerald/pull/1492) in pokeemerald for details. This also updates m4a_internal.h and m4a.c with pokeemerald's improved variable and label names.

Port CgbSound Documentation and Fakematch Fixes

---

src/pokemon.c

See https://github.com/pret/pokeruby/pull/837 for reference.

Add fix to disallow negative current HP values

---

data/battle_anim_scripts.s

This file should still be synced properly with pokeemerald in the future, but for now the magic numbers for the sound constants have been fixed.

Fix Magic Numbers in battle_anim_scripts.s

---

src/pokemon.c

Encountered these missing magic numbers while messing around expanding party size.

Fix party size calculations for larger-than-six PARTY_SIZE

---

INSTALL.md
docs/bugs_and_glitches.md
docs/legacy_WSL1_INSTALL.md
src/crt0.s

In an attempt to address frequently-encountered issues when setting up this project.

Sync INSTALL.md with Emerald

---

.github/calcrom/webhook.sh

Syncing with https://github.com/pret/pokeemerald/pull/1535

Add line breaks around webhook output

---

Makefile

Syncing with <https://github.com/pret/pokeemerald/pull/1274>

Update Makefile to not require gcc-arm-none-eabi

---

src/field_fadetransition.c

Some names were taken from https://github.com/ghoulslash/pokeemerald/commit/88575795199f65b4554a39019dd34a032518ac07

Document src/field_fadetransition.c

---

include/sprite.h

See https://github.com/pret/pokeemerald/pull/1656
Seems to be a leftover from pokeruby

Remove dead prototypes

---

data/field_effect_scripts.s

For the `git grep` users out there.

Add field effect constants as comments

---

include/overworld.h
src/cable_club.c
src/field_effect.c
src/field_fadetransition.c
src/item_use.c
src/main_menu.c
src/overworld.c
src/region_map.c

Also renamed uses of trade room to cable club and trading states to link states.

Document src/overworld.c

---

include/global.h
include/save.h
src/cereader_tool.c
src/hall_of_fame.c
src/save.c

Sync static asserts for save size from pokeemerald, as well as https://github.com/pret/pokeemerald/pull/1725 and some additional constant usage.

Sync save sector checks

---

include/battle.h
src/data/trainers.h

Syncing with https://github.com/pret/pokeemerald/pull/1717

Macros for keeping .partyFlags, .partySize, and .party in sync

---

ld_script.txt
ld_script_modern.txt

Sync ld script changes from https://github.com/pret/pokeemerald/pull/1738 and https://github.com/pret/pokeemerald/pull/1812.

Sync wildcards in ld scripts

---

src/data/pokemon_graphics/back_pic_coordinates.h
src/data/pokemon_graphics/front_pic_coordinates.h

Applies pokeemerald's style for mon pic coordinate data.
AsparagusEduardo#6051

Mon pic coordinates to macros

---

include/constants/metatile_labels.h

Syncing with <https://github.com/pret/pokeemerald/pull/1860>

Format metatile labels

---

include/battle.h
include/constants/battle_script_commands.h

Someone probably copy-pasted these from Pokeemerald. Since they do not match the contents of the BattleScripting Struct in Pokefirered, having them can be unnecessarily confusing for people who may want to add new variables to that struct and a matching constant label for their address.
Lunos#4026

Updated BattleScripting addresses

---

src/m4a_1.s

Clone of [#1987](https://github.com/pret/pokeemerald/pull/1927) from pokeemerald

Add Missing Constant Usage in m4a_1

---

src/shop.c

- Removes useless spaces
- gShopData to sShopData 
- Small documentation constants for mart types

Small mart changes

---

src/data/pokemon/experience_tables.h

Clone of [#1969](https://github.com/pret/pokeemerald/pull/1969) from pokeemerald.

Safeguard SQUARE and CUBE Macro Arguments in Parentheses

---

include/constants/metatile_labels.h

Sync with https://github.com/pret/pokeemerald/pull/1972

Remove non-existent tilesets from label comments and alphabetize

---

include/fieldmap.h
src/field_camera.c
src/shop.c

Adds NUM_TILES_PER_METATILE to make the lives of those converting their projects to triple layer easier

Add NUM_TILES_PER_METATILE
